### ISSUE TITLE
Exception while scraping getbootstrap.com with firefox

### ISSUE THREAD

**Issue by Corban-Lee** [Corban-Lee/Scalorize#3]
Scraping https://getbootstrap.com with Firefox via geckdriver.
I had already scraped the site partially with edge driver.

```
127.0.0.1 - - [07/Jun/2023 09:56:43] "GET /output/getbootstrap.com/2.3.2/1920%20firefox.png HTTP/1.1" 200 -
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "d:\Projects\WebShot\venv\Lib\site-packages\werkzeug\wsgi.py", line 289, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "d:\Projects\WebShot\venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
  File "D:\Projects\WebShot/WebShot\scrape.py", line 108, in stream_screenshots_generator
    for screenshot in screenshots:
  File "D:\Projects\WebShot/WebShot\scrape.py", line 144, in process_url
    self.scrape_urls_to_queue(driver, url)
  File "D:\Projects\WebShot/WebShot\scrape.py", line 164, in scrape_urls_to_queue
    hrefs = [anchor_tag.get_attribute("href") for anchor_tag in self.get_anchor_tags(driver)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\WebShot/WebShot\scrape.py", line 164, in <listcomp>
    hrefs = [anchor_tag.get_attribute("href") for anchor_tag in self.get_anchor_tags(driver)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\WebShot\venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 178, in get_attribute
    attribute_value = self.parent.execute_script(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\WebShot\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\WebShot\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "d:\Projects\WebShot\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element with the reference 3a707de3-efd1-48a7-8cd2-ca4705722dfb is stale; either its node document is not the active document, or it is no longer connected to the DOM
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:495:5
element.getKnownElement@chrome://remote/content/marionette/element.sys.mjs:508:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:233:33
cloneObject/result<@chrome://remote/content/marionette/json.sys.mjs:50:52
cloneObject@chrome://remote/content/marionette/json.sys.mjs:50:25
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:244:16
cloneObject@chrome://remote/content/marionette/json.sys.mjs:56:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:244:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:248:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:30
```

**Comment by Corban-Lee** [comment]
Outdated because the web scraper was rewritten in playwright
